import os
from dotenv import load_dotenv

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
load_dotenv(os.path.join(_PROJECT_ROOT, ".env"))

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MOONSHOT_API_KEY = os.getenv("MOONSHOT_API_KEY")
MOONSHOT_BASE_URL = os.getenv("MOONSHOT_BASE_URL", "https://api.moonshot.cn/v1")
KIMI_API_KEY = os.getenv("KIMI_API_KEY")

LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")
LANGCHAIN_TRACING_V2 = os.getenv("LANGCHAIN_TRACING_V2")
LANGCHAIN_PROJECT = os.getenv("LANGCHAIN_PROJECT")

LANGSMITH_API_KEY = os.getenv("LANGSMITH_API_KEY")
LANGSMITH_TRACING = os.getenv("LANGSMITH_TRACING")
LANGSMITH_PROJECT = os.getenv("LANGSMITH_PROJECT")

if LANGCHAIN_API_KEY and not LANGSMITH_API_KEY:
    os.environ["LANGSMITH_API_KEY"] = LANGCHAIN_API_KEY
    LANGSMITH_API_KEY = LANGCHAIN_API_KEY

if LANGCHAIN_PROJECT and not LANGSMITH_PROJECT:
    os.environ["LANGSMITH_PROJECT"] = LANGCHAIN_PROJECT
    LANGSMITH_PROJECT = LANGCHAIN_PROJECT

if LANGCHAIN_TRACING_V2 and not LANGSMITH_TRACING:
    os.environ["LANGSMITH_TRACING"] = LANGCHAIN_TRACING_V2
    LANGSMITH_TRACING = LANGCHAIN_TRACING_V2

NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USER = os.getenv("NEO4J_USER")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")
NEO4J_DATABASE = os.getenv("NEO4J_DATABASE")

MILVUS_HOST = os.getenv("MILVUS_HOST")
MILVUS_PORT = os.getenv("MILVUS_PORT")
MILVUS_URI = os.getenv("MILVUS_URI")
MILVUS_COLLECTION_NAME = os.getenv("MILVUS_COLLECTION_NAME")
MILVUS_DIMENSION = os.getenv("MILVUS_DIMENSION")

EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
LLM_MODEL = os.getenv("LLM_MODEL")
RERANKER_MODEL = os.getenv("RERANKER_MODEL")
BM25_TOP_K = os.getenv("BM25_TOP_K")
CHECKPOINTER_PATH = os.getenv("CHECKPOINTER_PATH")
RETRIEVAL_BALANCE_STRATEGY = os.getenv("RETRIEVAL_BALANCE_STRATEGY")
RETRIEVAL_TIMEOUT_SECONDS = os.getenv("RETRIEVAL_TIMEOUT_SECONDS")
RETRIEVE_EXPAND_FACTOR = os.getenv("RETRIEVE_EXPAND_FACTOR")
LIT_EXPAND_FACTOR = os.getenv("LIT_EXPAND_FACTOR")
GRAPH_EXPAND_FACTOR = os.getenv("GRAPH_EXPAND_FACTOR")
MAX_RETRIEVAL_TOP_K = os.getenv("MAX_RETRIEVAL_TOP_K")
MAX_GRAPH_ROWS = os.getenv("MAX_GRAPH_ROWS")
GRAPH_FALLBACK_MAX_NODES = os.getenv("GRAPH_FALLBACK_MAX_NODES")
RERANK_SIMPLE_SKIP_THRESHOLD = os.getenv("RERANK_SIMPLE_SKIP_THRESHOLD")
RERANK_SIMPLE_CANDIDATE_LIMIT = os.getenv("RERANK_SIMPLE_CANDIDATE_LIMIT")
RERANK_COMPLEX_CANDIDATE_LIMIT = os.getenv("RERANK_COMPLEX_CANDIDATE_LIMIT")
SIMPLE_CONTEXT_BUDGET_CHARS = os.getenv("SIMPLE_CONTEXT_BUDGET_CHARS")
COMPLEX_CONTEXT_BUDGET_CHARS = os.getenv("COMPLEX_CONTEXT_BUDGET_CHARS")
SIMPLE_PER_DOC_CHARS = os.getenv("SIMPLE_PER_DOC_CHARS")
COMPLEX_PER_DOC_CHARS = os.getenv("COMPLEX_PER_DOC_CHARS")
FAST_MODE = os.getenv("FAST_MODE")
FAST_EMBEDDING_MODEL = os.getenv("FAST_EMBEDDING_MODEL")
FAST_LLM_MODEL = os.getenv("FAST_LLM_MODEL")
FAST_RERANKER_MODEL = os.getenv("FAST_RERANKER_MODEL")
TOP_K = os.getenv("TOP_K")
TEMPERATURE = os.getenv("TEMPERATURE")
MAX_TOKENS = os.getenv("MAX_TOKENS")
CHUNK_SIZE = os.getenv("CHUNK_SIZE")
CHUNK_OVERLAP = os.getenv("CHUNK_OVERLAP")
MAX_GRAPH_DEPTH = os.getenv("MAX_GRAPH_DEPTH")
SESSION_ID = os.getenv("SESSION_ID")
