import os
from dotenv import load_dotenv

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
load_dotenv(os.path.join(_PROJECT_ROOT, ".env"))

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MOONSHOT_API_KEY = os.getenv("MOONSHOT_API_KEY")
MOONSHOT_BASE_URL = os.getenv("MOONSHOT_BASE_URL", "https://api.moonshot.cn/v1")
KIMI_API_KEY = os.getenv("KIMI_API_KEY")

LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")
LANGCHAIN_TRACING_V2 = os.getenv("LANGCHAIN_TRACING_V2")
LANGCHAIN_PROJECT = os.getenv("LANGCHAIN_PROJECT")

LANGSMITH_API_KEY = os.getenv("LANGSMITH_API_KEY")
LANGSMITH_TRACING = os.getenv("LANGSMITH_TRACING")
LANGSMITH_PROJECT = os.getenv("LANGSMITH_PROJECT")

if LANGCHAIN_API_KEY and not LANGSMITH_API_KEY:
    os.environ["LANGSMITH_API_KEY"] = LANGCHAIN_API_KEY
    LANGSMITH_API_KEY = LANGCHAIN_API_KEY

if LANGCHAIN_PROJECT and not LANGSMITH_PROJECT:
    os.environ["LANGSMITH_PROJECT"] = LANGCHAIN_PROJECT
    LANGSMITH_PROJECT = LANGCHAIN_PROJECT

if LANGCHAIN_TRACING_V2 and not LANGSMITH_TRACING:
    os.environ["LANGSMITH_TRACING"] = LANGCHAIN_TRACING_V2
    LANGSMITH_TRACING = LANGCHAIN_TRACING_V2

NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USER = os.getenv("NEO4J_USER")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")
NEO4J_DATABASE = os.getenv("NEO4J_DATABASE")

MILVUS_HOST = os.getenv("MILVUS_HOST")
MILVUS_PORT = os.getenv("MILVUS_PORT")
MILVUS_COLLECTION_NAME = os.getenv("MILVUS_COLLECTION_NAME")
MILVUS_DIMENSION = os.getenv("MILVUS_DIMENSION")

EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
LLM_MODEL = os.getenv("LLM_MODEL")
TOP_K = os.getenv("TOP_K")
TEMPERATURE = os.getenv("TEMPERATURE")
MAX_TOKENS = os.getenv("MAX_TOKENS")
CHUNK_SIZE = os.getenv("CHUNK_SIZE")
CHUNK_OVERLAP = os.getenv("CHUNK_OVERLAP")
MAX_GRAPH_DEPTH = os.getenv("MAX_GRAPH_DEPTH")
